//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPRSimulTrain.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPRSimulTrain.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        internal static string AlertFirstQuestionHd {
            get {
                return ResourceManager.GetString("AlertFirstQuestionHd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally:
        ///30 CPR&apos;s, Breath-of-Life, next 30 CPR&apos;s
        ///But here and now?
        ///Just so many sets of 30 CPR&apos;s each.
        ///.
        /// </summary>
        internal static string AlertFisrtQuestion {
            get {
                return ResourceManager.GetString("AlertFisrtQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string Base_Private {
            get {
                return ResourceManager.GetString("Base Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BaseAbout {
            get {
                return ResourceManager.GetString("BaseAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (2019,2020)
        ///CNG Internet Software, LLC
        ///All Rights Reserved.
        /// </summary>
        internal static string BaseAboutCopy {
            get {
                return ResourceManager.GetString("BaseAboutCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Name.:.
        /// </summary>
        internal static string BaseAboutName {
            get {
                return ResourceManager.GetString("BaseAboutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. Number.:.
        /// </summary>
        internal static string BaseAboutReg {
            get {
                return ResourceManager.GetString("BaseAboutReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.:.
        /// </summary>
        internal static string BaseAboutRelease {
            get {
                return ResourceManager.GetString("BaseAboutRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string BaseAboutTitle {
            get {
                return ResourceManager.GetString("BaseAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.:.
        /// </summary>
        internal static string BaseAboutVersion {
            get {
                return ResourceManager.GetString("BaseAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CNG Internet Software, LLC.
        ///  46 Village Ct.
        ///  Hazlet, NJ, 07730
        ///
        ///  Support@cngInternet.com
        /// (973) 287-9862
        ///
        ///  App version: 2.1.14.8
        ///.
        /// </summary>
        internal static string BaseContactAddress {
            get {
                return ResourceManager.GetString("BaseContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message .. .. ...
        /// </summary>
        internal static string BaseContactContactMsg {
            get {
                return ResourceManager.GetString("BaseContactContactMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Email: .
        /// </summary>
        internal static string BaseContactEmail {
            get {
                return ResourceManager.GetString("BaseContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email, optional.
        /// </summary>
        internal static string BaseContactEmailOptional {
            get {
                return ResourceManager.GetString("BaseContactEmailOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch.
        /// </summary>
        internal static string BaseContactGetinTouch {
            get {
                return ResourceManager.GetString("BaseContactGetinTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CNG Internet Software, LLC
        ///Matawan, NJ
        ///(973) 287-9862
        ///Service@CNGInternet.com
        ///.
        /// </summary>
        internal static string BaseContactLocation {
            get {
                return ResourceManager.GetString("BaseContactLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Message: .
        /// </summary>
        internal static string BaseContactMessage {
            get {
                return ResourceManager.GetString("BaseContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string BaseContactName {
            get {
                return ResourceManager.GetString("BaseContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, optional.
        /// </summary>
        internal static string BaseContactNameOptional {
            get {
                return ResourceManager.GetString("BaseContactNameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Some of my comments.
        ///
        ///.
        /// </summary>
        internal static string BaseContactNowTime {
            get {
                return ResourceManager.GetString("BaseContactNowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string BaseContactSend {
            get {
                return ResourceManager.GetString("BaseContactSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Message re: &apos;CPR Simulation &amp; Training&apos;.
        /// </summary>
        internal static string BaseContactSubject1 {
            get {
                return ResourceManager.GetString("BaseContactSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string BaseContactTitle {
            get {
                return ResourceManager.GetString("BaseContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string BaseContactUs {
            get {
                return ResourceManager.GetString("BaseContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message .. .. ...
        /// </summary>
        internal static string BaseContactYourMessage {
            get {
                return ResourceManager.GetString("BaseContactYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use Agreement:.
        /// </summary>
        internal static string BaseDisclaimerTerms {
            get {
                return ResourceManager.GetString("BaseDisclaimerTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A) This [agreement] is entered between and by you and the author of this app. The use of the app is subject to the terms amd conditions of this agreement..
        /// </summary>
        internal static string BaseDisclaimerTermsA {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B) The information contained on these application pages is for informational purposes only and no warranty is made that the information is error-free. The information contained within the application pages may be, at any time, outdated and may include inaccuracies and/or errors. Information may change at any time without notice..
        /// </summary>
        internal static string BaseDisclaimerTermsB {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-1) NEITHER COMPANY, NOR ANY OF ITS SUBSIDIARIES, AFFILIATES, EMPLOYEES, AGENTS, LICENSORS OR CONTENT PROVIDERS  MAKES ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND REGARDING ITS APPLICATION, THE CONTENT OR ANY SERVICE PROVIDED HEREIN..
        /// </summary>
        internal static string BaseDisclaimerTermsC1 {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-2) NEITHER COMPANY, NOR ANY OF ITS SUBSIDIARIES, AFFILIATES, EMPLOYEES, AGENTS, LICENSORS OR CONTENT PROVIDERS  MAKES ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND REGARDING ITS APPLICATION, THE CONTENT OR ANY SERVICE PROVIDED HEREIN..
        /// </summary>
        internal static string BaseDisclaimerTermsC2 {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-3) THE CONTENT AND SERVICES ARE PROVIDED ON AN &apos;AS IS&apos; BASIS AND COMPANY SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING WITHOUT LIMITATION, WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, WARRANTIES OF MERCHANTABILITY OR WARRANTIES AGAINST INFRINGEMENT..
        /// </summary>
        internal static string BaseDisclaimerTermsC3 {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-4) COMPANY, ITS SUBSIDIARIES, AFFILIATES, EMPLOYEES, AGENTS, LICENSORS AND CONTENT PROVIDERS SHALL NOT BE LIABLE FOR ANY DAMAGES OR LOSSES, MEDICAL EMERGENCIES, INJURIES, OR DEATH, WITHOUT LIMITATION, INDIRECT, CONSEQUENTIAL, SPECIAL, RESULTING FROM OR CAUSED BY THE COMPANY&apos;S APPLICATION, THEIR CONTENT, ANY SERVICES PROVIDED HEREIN OR THE DELAY OR INABILITY TO USE THE COMPANY&apos;S APPLICATION, OR ANY INFORMATION, MATERIALS, SOFTWARE, PRODUCTS AND SERVICES OBTAINED THROUGH THIS APPLICATION, OR OTHERWISE ARISI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseDisclaimerTermsC4 {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D) THE COMPANY DOES NOT REPRESENT OR ENDORSE THE ACCURACY OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT, OR OTHER INFORMATION DISPLAYED OR DISTRIBUTED THROUGH THE APPLICATION.YOU ACKNOWLEDGE THAT ANY RELIANCE UPON SUCH OPINION, ADVICE, STATEMENT, MEMORANDUM, OR INFORMATION SHALL BE AT YOUR SOLE RISK.THE COMPANY RESERVES THE RIGHT AT ALL TIMES TO DISCLOSE ANY INFORMATION AS NECESSARY TO SATISFY ANY LAW, REGULATION OR GOVERNMENT REQUEST, OR TO EDIT, REFUSE TO POST OR TO REMOVE ANY INFORMATION OR MATERIALS, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseDisclaimerTermsD {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E) Company does not assume any responsibility or risk for your use of the Company&apos;s application content, websites, or mobile application(s), and will in no event be liable to you or anyone else for any decision made or action taken by you or anyone else in reliance upon the information provided through Company&apos;s application content, websites, or mobile application(s)..
        /// </summary>
        internal static string BaseDisclaimerTermsE {
            get {
                return ResourceManager.GetString("BaseDisclaimerTermsE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Disclaimer.
        /// </summary>
        internal static string BaseDisclaimerTitle {
            get {
                return ResourceManager.GetString("BaseDisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string BaseFeedback {
            get {
                return ResourceManager.GetString("BaseFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Email:.
        /// </summary>
        internal static string BaseFeedbackEmail {
            get {
                return ResourceManager.GetString("BaseFeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email, optional.
        /// </summary>
        internal static string BaseFeedbackEmailOptional {
            get {
                return ResourceManager.GetString("BaseFeedbackEmailOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Feedback to Us.
        /// </summary>
        internal static string BaseFeedbackFeedbToUs {
            get {
                return ResourceManager.GetString("BaseFeedbackFeedbToUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Message:.
        /// </summary>
        internal static string BaseFeedbackMessage {
            get {
                return ResourceManager.GetString("BaseFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, optional.
        /// </summary>
        internal static string BaseFeedbackNameOptional {
            get {
                return ResourceManager.GetString("BaseFeedbackNameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Feedback is very much appreciated.
        ///If you will also submit your email (kept just by us) we will let you know ASP what happen next.
        ///
        ///CNG Internet Software, LLC.
        ///Support@cngInternet.com
        ///.
        /// </summary>
        internal static string BaseFeedbackNote {
            get {
                return ResourceManager.GetString("BaseFeedbackNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///I have some suggestions to improve this app.:
        ///
        ///Name:.
        /// </summary>
        internal static string BaseFeedbackNowTime {
            get {
                return ResourceManager.GetString("BaseFeedbackNowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string BaseFeedBackSEND {
            get {
                return ResourceManager.GetString("BaseFeedBackSEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Message re: &apos;CPR Simulation / Training&apos;.
        /// </summary>
        internal static string BaseFeedbackSubject {
            get {
                return ResourceManager.GetString("BaseFeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Feedback.
        /// </summary>
        internal static string BaseFeedBackTitle {
            get {
                return ResourceManager.GetString("BaseFeedBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Feedback.
        /// </summary>
        internal static string BaseFeedbackYourFeedback {
            get {
                return ResourceManager.GetString("BaseFeedbackYourFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Disclaimer.
        /// </summary>
        internal static string BaseLegal {
            get {
                return ResourceManager.GetString("BaseLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We collect NO personal information. 
        ///We collect NO payment information. 
        ///We collect NO Social Media Login Data. 
        ///We collect NO automatic data, such as IP addresses or device characteristics. 
        ///We collect NO private, personal information from other sources..
        /// </summary>
        internal static string BasePrivacyBody1 {
            get {
                return ResourceManager.GetString("BasePrivacyBody1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a resident of California, you are covered by California Civil Code Section 1798.83, known as the &quot;Shine The Light&quot; law. Your Rights include the request, free, once a year, of specific Information about personal Information if any collected. 
        ///Please contact us via email at service@CNGInternetSoftware.com regarding CA 1798.83.
        /// </summary>
        internal static string BasePrivacyBody10 {
            get {
                return ResourceManager.GetString("BasePrivacyBody10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, whenever it is necessary to stay legal. An updated &quot;Revised&quot; date will indicate the updated version..
        /// </summary>
        internal static string BasePrivacyBody11 {
            get {
                return ResourceManager.GetString("BasePrivacyBody11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any questions, any comments, please email us at Service@CNGInternetSoftware.com..
        /// </summary>
        internal static string BasePrivacyBody12 {
            get {
                return ResourceManager.GetString("BasePrivacyBody12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are not processing any personal, private information at all.
        /// </summary>
        internal static string BasePrivacyBody2 {
            get {
                return ResourceManager.GetString("BasePrivacyBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BasePrivacyBody3 {
            get {
                return ResourceManager.GetString("BasePrivacyBody3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BasePrivacyBody4 {
            get {
                return ResourceManager.GetString("BasePrivacyBody4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BasePrivacyBody5 {
            get {
                return ResourceManager.GetString("BasePrivacyBody5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BasePrivacyBody6 {
            get {
                return ResourceManager.GetString("BasePrivacyBody6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string BasePrivacyBody7 {
            get {
                return ResourceManager.GetString("BasePrivacyBody7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although we do not collect any information, you may contact us at service@CNGInternetSoftware.com regarding any discussion regarding privacy and personal data..
        /// </summary>
        internal static string BasePrivacyBody8 {
            get {
                return ResourceManager.GetString("BasePrivacyBody8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do-Not-Track (DNT) technology for mobile applications is not yet uniformly implemented. We currently do not recognize, collect, and process and respond to DNT..
        /// </summary>
        internal static string BasePrivacyBody9 {
            get {
                return ResourceManager.GetString("BasePrivacyBody9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. WHAT INFORMATION DO WE COLLECT?.
        /// </summary>
        internal static string BasePrivacyHead1 {
            get {
                return ResourceManager.GetString("BasePrivacyHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. CALIFORNIA RESIDENTS PRIVACY RIGHTS?.
        /// </summary>
        internal static string BasePrivacyHead10 {
            get {
                return ResourceManager.GetString("BasePrivacyHead10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. DO WE MAKE UPDATES TO THIS POLICY?.
        /// </summary>
        internal static string BasePrivacyHead11 {
            get {
                return ResourceManager.GetString("BasePrivacyHead11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. HOW CAN YOU CONTACT US ABOUT THIS POLICY?.
        /// </summary>
        internal static string BasePrivacyHead12 {
            get {
                return ResourceManager.GetString("BasePrivacyHead12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. HOW DO WE USE YOUR INFORMATION?.
        /// </summary>
        internal static string BasePrivacyHead2 {
            get {
                return ResourceManager.GetString("BasePrivacyHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?.
        /// </summary>
        internal static string BasePrivacyHead3 {
            get {
                return ResourceManager.GetString("BasePrivacyHead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. WHAT ABOUT COOKIES AND OTHER TRACKING TECHNOLOGIES?.
        /// </summary>
        internal static string BasePrivacyHead4 {
            get {
                return ResourceManager.GetString("BasePrivacyHead4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Does this software have/use logins from Social Media?.
        /// </summary>
        internal static string BasePrivacyHead5 {
            get {
                return ResourceManager.GetString("BasePrivacyHead5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. IS YOUR INFORMATION TRANSFERRED INTERNATIONALLY?.
        /// </summary>
        internal static string BasePrivacyHead6 {
            get {
                return ResourceManager.GetString("BasePrivacyHead6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. DO WE COLLECT INFORMATION FROM MINORS?.
        /// </summary>
        internal static string BasePrivacyHead7 {
            get {
                return ResourceManager.GetString("BasePrivacyHead7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. WHAT ARE YOUR PRIVACY RIGHTS?.
        /// </summary>
        internal static string BasePrivacyHead8 {
            get {
                return ResourceManager.GetString("BasePrivacyHead8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. DO WE RESPOND TO DO-NOT-TRACK SIGNALS?.
        /// </summary>
        internal static string BasePrivacyHead9 {
            get {
                return ResourceManager.GetString("BasePrivacyHead9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated [January 1st, 2020].
        /// </summary>
        internal static string BasePrivacyLastUpdate {
            get {
                return ResourceManager.GetString("BasePrivacyLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you downloading our mobile software. We will protect your Personal Information and your right to privacy. Any questions regarding your Personal Information, please contact us at service@CNGInternetSoftware.com
        ///This document will describe our privacy policy. We will explain to you what Information, if any, we collect, how it is (if received) used, and what your rights are. In case you do not agree with our Privacy Policy, please stop using this application.
        ///This privacy policy applies to all collecte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasePrivacyMainBody {
            get {
                return ResourceManager.GetString("BasePrivacyMainBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string BasePrivacyTitle {
            get {
                return ResourceManager.GetString("BasePrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Notice.
        /// </summary>
        internal static string BasePrivacyTopHead {
            get {
                return ResourceManager.GetString("BasePrivacyTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share This App.
        /// </summary>
        internal static string BaseShare {
            get {
                return ResourceManager.GetString("BaseShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share This App.
        /// </summary>
        internal static string BaseShare1 {
            get {
                return ResourceManager.GetString("BaseShare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found this new app
        ///[CPR Simulation and Trainer].
        ///Try it for yourself.
        ///[ https://www.cnginternetsoftware.com/smart_phone_software ].
        /// </summary>
        internal static string BaseShareFound {
            get {
                return ResourceManager.GetString("BaseShareFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Share Options.
        /// </summary>
        internal static string BaseShareGetOption {
            get {
                return ResourceManager.GetString("BaseShareGetOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This new app lets you simulate CPR&apos;s on a pile of towels, or one, two pillows.
        ///
        ///Yes, it keeps track of count, and tells you about correct depth.
        ///
        ///Guess what, here is one of my runs:
        ///On:.
        /// </summary>
        internal static string BaseShareMsg1 {
            get {
                return ResourceManager.GetString("BaseShareMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a BEST RATE of.
        /// </summary>
        internal static string BaseShareMsg2 {
            get {
                return ResourceManager.GetString("BaseShareMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correct CPR&apos;s.
        ///Take a look at.
        /// </summary>
        internal static string BaseShareMsg3 {
            get {
                return ResourceManager.GetString("BaseShareMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///If you think that this app could be of use to someone else,
        ///why not send a brief note and let that person know..
        /// </summary>
        internal static string BaseShareNote {
            get {
                return ResourceManager.GetString("BaseShareNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This new app lets you simulate CPR&apos;s on a pile of towels, or one, two pillows.
        ///Yes, it keeps track of count, and tells you about correct depth
        ///
        ///Take a look at 
        ///[https://www.cnginternetsoftware.com/smart_phone_software ].
        /// </summary>
        internal static string BaseShareText {
            get {
                return ResourceManager.GetString("BaseShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This new app lets you simulate CPR&apos;s on a pile of towels, or one, two pillows.
        ///Yes, it keeps track of count, and tells you about correct depth
        ///
        ///Take a look at 
        ///[https://www.cnginternetsoftware.com/smart_phone_software ].
        /// </summary>
        internal static string BaseShareText1 {
            get {
                return ResourceManager.GetString("BaseShareText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this App.
        /// </summary>
        internal static string BaseShareTitle {
            get {
                return ResourceManager.GetString("BaseShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Text.
        /// </summary>
        internal static string BaseShareTitle2 {
            get {
                return ResourceManager.GetString("BaseShareTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide - Help.
        /// </summary>
        internal static string BaseUserGuide {
            get {
                return ResourceManager.GetString("BaseUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question about battery life..
        /// </summary>
        internal static string BaseUserGuide_2_BatteryHD1 {
            get {
                return ResourceManager.GetString("BaseUserGuide_2_BatteryHD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Use - CPR Compressions.
        /// </summary>
        internal static string BaseUserGuide_2_DoingCPRHD1 {
            get {
                return ResourceManager.GetString("BaseUserGuide_2_DoingCPRHD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide - CPR Simul. / Training.
        /// </summary>
        internal static string BaseUserGuide_2_DoingCPRTitle {
            get {
                return ResourceManager.GetString("BaseUserGuide_2_DoingCPRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide - Start Page.
        /// </summary>
        internal static string BaseUserGuide_P1Titel {
            get {
                return ResourceManager.GetString("BaseUserGuide_P1Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Question? Our Promise:
        ///
        ///Our app will:
        ///1) start timer and accelerometer only once the simulation page is up
        ///2) stop all this the moment you leave the simulation
        ///3) DO NOT have a timer and accelerometer just running in the background to be &apos;ready.&apos;
        ///
        ///Result?
        ///The CPR Simulation app uses just about 0.1% of battery power per hour of continous use..
        /// </summary>
        internal static string BaseUserGuideBattery {
            get {
                return ResourceManager.GetString("BaseUserGuideBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3)  Question about battery life..
        /// </summary>
        internal static string BaseUserGuideBatteryHD {
            get {
                return ResourceManager.GetString("BaseUserGuideBatteryHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are the Displays correct?.
        /// </summary>
        internal static string BaseUserGuideDisplayHD {
            get {
                return ResourceManager.GetString("BaseUserGuideDisplayHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To simulate the CPR activities we use the phone embedded 3-axis accelerometer, measuring all 3 &apos;forces&apos; of acceleration. It gives data-reads about 3,000 times a minute. Yes, VERY sensitive.
        ///
        ///Two (of three) effects can be tested quickly. Tilt the device in every whatsoever direction a bit while the [CPR Simulator] screen is up, and a red display will tell you &quot;No CPR - Not Flat -&quot; (Press [Start Again] if needed). A tilted device is an incorrect device.
        ///
        ///
        ///We installed software filters, accounting for thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseUserGuideDisplays {
            get {
                return ResourceManager.GetString("BaseUserGuideDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top frame has (3) parts:
        ///
        ///(1) Recording &quot;Breath of Life&quot;
        ///Rescue breathing is no longer required in layperson CPR emergencies. But. There are still emergency scenarios which call for rescue breathing. So, we simulate the count, and the Breathing Sets (30 CPR&apos;s each), and show the counters.
        ///
        ///(2) A message telling you what your most current CPR compress (down push) would be in a real situation (&quot;Correct,&quot; &quot;Too Flat,&quot; i.e., not deep enough, or &quot;Too Deep,&quot; i.e., a dangerously (2.4&quot; +).
        ///
        ///(3) A button t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseUserGuideDoingCPR {
            get {
                return ResourceManager.GetString("BaseUserGuideDoingCPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) App Page: [Start Simulation ].
        /// </summary>
        internal static string BaseUserGuideDoingCPRHD {
            get {
                return ResourceManager.GetString("BaseUserGuideDoingCPRHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic. 1.
        /// </summary>
        internal static string BaseUserGuidePillows1 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillows1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pic. 2.
        /// </summary>
        internal static string BaseUserGuidePillows2 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillows2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to simulate CPR compressions.
        /// </summary>
        internal static string BaseUserGuidePillowsHD {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So. Simulating CPR..
        /// </summary>
        internal static string BaseUserGuidePillowsText5 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a set of towels, pillows, something cushy to simulate a human chest. Fold your two hands, as shown in Pic. 1 on top of this &apos;chest&apos;. Ready!
        ///Start the Simulation: 100 CPR compressions into the towels per minute, about 2.4 inches deep..
        /// </summary>
        internal static string BaseUserGuidePillowsText51 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How? The Hands - two versions.
        /// </summary>
        internal static string BaseUserGuidePillowsText52 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) &apos;Officially?&apos; OK, you remember the CPR &apos;hands&apos; (Pic 1).
        ///The CPR-hands hold the edge of the phone (Pic 2). Run the app. The app will do the leading beeps (100/min), you do the compressions, it&apos;s all recorded, like &quot;It&apos;s a-ok,&quot; or &quot;No, not OK&quot;..
        /// </summary>
        internal static string BaseUserGuidePillowsText53 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) &apos;The-Easy-Way?&apos; Still OK. Put just the lower CPR-hand flat on the towels, the phone on top; run the app, and do the compressions, the recordings..
        /// </summary>
        internal static string BaseUserGuidePillowsText531 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem?.
        /// </summary>
        internal static string BaseUserGuidePillowsText54 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. Today&apos;s smartphones are too smart. Every time you put your hand closely over the phone screen, the display changes. Bummer. Please follow what you see in Pic. 2; 
        ///EITHER -- phone still between the two hands, but let it half-way or more stick out. Use your thumb to press the required buttons or switches. 
        ///OR -- Use just the bottom hand, and put the phone on top. Use the other (free) hand to run the app. Not true CPR, but will meassure tempo and depth accurately..
        /// </summary>
        internal static string BaseUserGuidePillowsText55 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Thankyou for you efforts to deepen you understanding of CPR..
        /// </summary>
        internal static string BaseUserGuidePillowsText56 {
            get {
                return ResourceManager.GetString("BaseUserGuidePillowsText56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Best CPR Simulation]
        ///
        ///The data in this section is from the list of saved CPR sessions, and is the best result measured against &quot;correct CPR&apos;s.&quot;
        ///
        ///
        ///Congratulation
        ///
        ///Press [Share Option], and you can send an email to your friend that includes the data from the [Best CPR Simulation]. A little bragging, but hey, you did great.
        ///
        ///
        ///The List of Results
        ///
        ///A DB based list of all previous CPR sessions. Sorted by date. Press an individual record to have an option to delete that record..
        /// </summary>
        internal static string BaseUserGuideResults {
            get {
                return ResourceManager.GetString("BaseUserGuideResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Note:
        ///TAP a list-record to manage / DELETE that reocrd.
        ///.
        /// </summary>
        internal static string BaseUserGuideResults1 {
            get {
                return ResourceManager.GetString("BaseUserGuideResults1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2) App Page [ Results ].
        /// </summary>
        internal static string BaseUserGuideResultsHD {
            get {
                return ResourceManager.GetString("BaseUserGuideResultsHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide - Simul. Results.
        /// </summary>
        internal static string BaseUserGuideResultsTitle {
            get {
                return ResourceManager.GetString("BaseUserGuideResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are trying to simulate CPR compressions, record them, and maybe share the best result..
        /// </summary>
        internal static string BaseUserGuideStart0 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. Preparing.
        /// </summary>
        internal static string BaseUserGuideStart01 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulating a human chest.......
        ///(1) Get a bunch of towels, pillows, a bunch of sweaters.
        ///The CPR&apos;s.......
        ///(2) Fold your hands resting on top of the towels / pillows / sweaters.
        ///See &lt;How to Simulate...&gt;, next pull-down..
        /// </summary>
        internal static string BaseUserGuideStart02 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. Action, CPR compressions.
        /// </summary>
        internal static string BaseUserGuideStart03 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Have the phone in-between your hands. See &lt;How to Simulate...&gt;, next pull-down.
        ///(2) Start the app, using a thumb to control things
        ///(3) At each beep, you need to do a compression (about 2.4 inches, 100 a minute)
        ///(4) When it is time, press the [ Save Result ] button
        ///(5) Just in case you want to run another CPR session, press [ Start Again ].
        /// </summary>
        internal static string BaseUserGuideStart04 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. Results.
        /// </summary>
        internal static string BaseUserGuideStart05 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot; Results &quot; page shows:
        /// -- &quot;Best CPR Simulation&quot;, allowing you to share your best CPR session result with a friend
        /// -- a list of all your CPR session results, sorted by date.
        /// </summary>
        internal static string BaseUserGuideStart06 {
            get {
                return ResourceManager.GetString("BaseUserGuideStart06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Usage.
        /// </summary>
        internal static string BaseUserGuideStartHD {
            get {
                return ResourceManager.GetString("BaseUserGuideStartHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        internal static string BaseUserGuideTitle {
            get {
                return ResourceManager.GetString("BaseUserGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is it?.
        /// </summary>
        internal static string BaseUserGuideWhatIsItHD {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is.
        /// </summary>
        internal static string BaseUserGuideWhatIsItText000 {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItText000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an audio and visual guide that trains you to do CPR compressions correctly. Correctly is 100 - 120 compressions per minute, about 2.4 inches deep (Adults).
        /// </summary>
        internal static string BaseUserGuideWhatIsItText001 {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItText001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW does the app help?.
        /// </summary>
        internal static string BaseUserGuideWhatIsItText002 {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItText002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) The app beeps at a 100/min rate, and you should do a compress at every beep.
        ///(2) The app monitors your compression &apos;depth&apos; and displays &quot;Correct&quot; for about 2.4\&quot;, &quot;To Flat&quot; for &lt;2.4\&quot;, &quot;Too Deep&quot; for &gt;2.4\&quot;
        ///(3) At the end of a &apos;run&apos; you can record the results.
        ///(4) The app allows you to text your best result to a friend..
        /// </summary>
        internal static string BaseUserGuideWhatIsItText003 {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItText003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check [ How to simulate CPR Compressions ].
        /// </summary>
        internal static string BaseUserGuideWhatIsItText004 {
            get {
                return ResourceManager.GetString("BaseUserGuideWhatIsItText004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Compressions / minute (Adults).
        /// </summary>
        internal static string CPR100Count {
            get {
                return ResourceManager.GetString("CPR100Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beeper
        ///Active:.
        /// </summary>
        internal static string CPRBeeperHdr {
            get {
                return ResourceManager.GetString("CPRBeeperHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At:.
        /// </summary>
        internal static string CPRResultAt {
            get {
                return ResourceManager.GetString("CPRResultAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best CPR Simulation.
        /// </summary>
        internal static string CPRResultBest {
            get {
                return ResourceManager.GetString("CPRResultBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation.
        /// </summary>
        internal static string CPRResultCongratulation {
            get {
                return ResourceManager.GetString("CPRResultCongratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct CPR&apos;s.
        /// </summary>
        internal static string CPRResultCorrect {
            get {
                return ResourceManager.GetString("CPRResultCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Profile with:
        ///
        ///Date / Time:.
        /// </summary>
        internal static string CPRResultData1 {
            get {
                return ResourceManager.GetString("CPRResultData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Compressions to Deep.........:.
        /// </summary>
        internal static string CPRResultDeepData {
            get {
                return ResourceManager.GetString("CPRResultDeepData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CPRResultDeleteCancel {
            get {
                return ResourceManager.GetString("CPRResultDeleteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting CPR Simulation Record.
        /// </summary>
        internal static string CPRResultDeleteData {
            get {
                return ResourceManager.GetString("CPRResultDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Good Compressions.............:.
        /// </summary>
        internal static string CPRResultGoodData {
            get {
                return ResourceManager.GetString("CPRResultGoodData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Yet.
        /// </summary>
        internal static string CPRResultNoData {
            get {
                return ResourceManager.GetString("CPRResultNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On:.
        /// </summary>
        internal static string CPRResultOn {
            get {
                return ResourceManager.GetString("CPRResultOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save
        ///
        ///
        ///
        ///
        ///CPR&apos;s.
        /// </summary>
        internal static string CPRResultSave {
            get {
                return ResourceManager.GetString("CPRResultSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Compressions too Shallow..:.
        /// </summary>
        internal static string CPRResultShallowData {
            get {
                return ResourceManager.GetString("CPRResultShallowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Options.
        /// </summary>
        internal static string CPRResultShareOption {
            get {
                return ResourceManager.GetString("CPRResultShareOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string CPRResultTitle {
            get {
                return ResourceManager.GetString("CPRResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why not share this good news with a friend?.
        /// </summary>
        internal static string CPRResultWhyNot {
            get {
                return ResourceManager.GetString("CPRResultWhyNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        internal static string CPRResultYesDelete {
            get {
                return ResourceManager.GetString("CPRResultYesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You had:.
        /// </summary>
        internal static string CPRResultYouHad {
            get {
                return ResourceManager.GetString("CPRResultYouHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated\n-At Rest-.
        /// </summary>
        internal static string CPRSimulActivated {
            get {
                return ResourceManager.GetString("CPRSimulActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Panel.
        /// </summary>
        internal static string CPRSimulAdvice {
            get {
                return ResourceManager.GetString("CPRSimulAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string CPRSimulAdvice1 {
            get {
                return ResourceManager.GetString("CPRSimulAdvice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Rescue Breath (1 per 30 CPR&apos;s).
        /// </summary>
        internal static string CPRSimulBreath {
            get {
                return ResourceManager.GetString("CPRSimulBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CPRSimulCancel {
            get {
                return ResourceManager.GetString("CPRSimulCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct CPR.
        /// </summary>
        internal static string CPRSimulCorrect {
            get {
                return ResourceManager.GetString("CPRSimulCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        internal static string CPRSimulGotit {
            get {
                return ResourceManager.GetString("CPRSimulGotit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Start CPR
        ///Simulation?.
        /// </summary>
        internal static string CPRSimulHdr {
            get {
                return ResourceManager.GetString("CPRSimulHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -No CPR-\nNOT Flat.
        /// </summary>
        internal static string CPRSimulLayFlat {
            get {
                return ResourceManager.GetString("CPRSimulLayFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Actions.
        /// </summary>
        internal static string CPRSimulNoAction {
            get {
                return ResourceManager.GetString("CPRSimulNoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - No CPR -.
        /// </summary>
        internal static string CPRSimulNoCPR {
            get {
                return ResourceManager.GetString("CPRSimulNoCPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device seems to process accelerometer output too slow.
        ///
        ///Application will continue, but results could be negatively impacted.
        ///.
        /// </summary>
        internal static string CPRSimulPopupmsg {
            get {
                return ResourceManager.GetString("CPRSimulPopupmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential CPR&apos;s.
        /// </summary>
        internal static string CPRSimulPotential {
            get {
                return ResourceManager.GetString("CPRSimulPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string CPRSimulPrep {
            get {
                return ResourceManager.GetString("CPRSimulPrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ready -.
        /// </summary>
        internal static string CPRSimulReady {
            get {
                return ResourceManager.GetString("CPRSimulReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string CPRSimulReset {
            get {
                return ResourceManager.GetString("CPRSimulReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Compressions .. .. .. .. .:.
        /// </summary>
        internal static string CPRSimulResultdata11 {
            get {
                return ResourceManager.GetString("CPRSimulResultdata11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressions too Shallow...:.
        /// </summary>
        internal static string CPRSimulResultdata22 {
            get {
                return ResourceManager.GetString("CPRSimulResultdata22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressions too Deep .. .. :.
        /// </summary>
        internal static string CPRSimulResultdata33 {
            get {
                return ResourceManager.GetString("CPRSimulResultdata33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Simulated Training Result.
        /// </summary>
        internal static string CPRSimulResultMsg1 {
            get {
                return ResourceManager.GetString("CPRSimulResultMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///No CPR Simulation Result available.
        ///______________________________________
        ///
        ///Please run a set of simulated CPR&apos;s
        ///
        ///            + &quot;    and try again.\n.
        /// </summary>
        internal static string CPRSimulResultMsg2 {
            get {
                return ResourceManager.GetString("CPRSimulResultMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Adding CPR Simulation Results:
        /// __________________________________
        ///
        ///.
        /// </summary>
        internal static string CPRSimulResultstm {
            get {
                return ResourceManager.GetString("CPRSimulResultstm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Save.
        /// </summary>
        internal static string CPRSimulResultYes {
            get {
                return ResourceManager.GetString("CPRSimulResultYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE RESULT.
        /// </summary>
        internal static string CPRSimulSaveResult {
            get {
                return ResourceManager.GetString("CPRSimulSaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START AGAIN.
        /// </summary>
        internal static string CPRSimulStartAgain {
            get {
                return ResourceManager.GetString("CPRSimulStartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Simulator.
        /// </summary>
        internal static string CPRSimulTitle {
            get {
                return ResourceManager.GetString("CPRSimulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Deep.
        /// </summary>
        internal static string CPRSimulTooDeep {
            get {
                return ResourceManager.GetString("CPRSimulTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Shallow.
        /// </summary>
        internal static string CPRSimulTooFlat {
            get {
                return ResourceManager.GetString("CPRSimulTooFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        Voice
        ///message:.
        /// </summary>
        internal static string CPRSoundHdr {
            get {
                return ResourceManager.GetString("CPRSoundHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test:.
        /// </summary>
        internal static string CPRTestResultshdr {
            get {
                return ResourceManager.GetString("CPRTestResultshdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Simulation.
        /// </summary>
        internal static string EntryMainDoSimul {
            get {
                return ResourceManager.GetString("EntryMainDoSimul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string EntryMainHDR01 {
            get {
                return ResourceManager.GetString("EntryMainHDR01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Simulation
        ///&amp; Training.
        /// </summary>
        internal static string EntryMainHDR02 {
            get {
                return ResourceManager.GetString("EntryMainHDR02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time - Real Count - Real Depth.
        /// </summary>
        internal static string EntryMainHDR03 {
            get {
                return ResourceManager.GetString("EntryMainHDR03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string EntryMainResults {
            get {
                return ResourceManager.GetString("EntryMainResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR - Realtime Simulation.
        /// </summary>
        internal static string EntryMainTitle {
            get {
                return ResourceManager.GetString("EntryMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Results        OK      Too       Too
        ///     Date Time               CPR&apos;s     Flat     Deep.
        /// </summary>
        internal static string ResultHDR {
            get {
                return ResourceManager.GetString("ResultHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nAre you sure you want to exit?.
        /// </summary>
        internal static string SuperExitMsg {
            get {
                return ResourceManager.GetString("SuperExitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        internal static string SuperExitNotNow {
            get {
                return ResourceManager.GetString("SuperExitNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit from \&quot;CPR Simulator\&quot;.
        /// </summary>
        internal static string SuperExitTitle {
            get {
                return ResourceManager.GetString("SuperExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string SuperExitYes {
            get {
                return ResourceManager.GetString("SuperExitYes", resourceCulture);
            }
        }
    }
}
